
name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install cppcheck
        run: sudo apt-get -y install cppcheck
      - name: Cppcheck code
        run: |
          mkdir MiniProject_C/3_Implementation/build_actions
          touch result_cppcheck.txt
          cppcheck MiniProject_C/3_Implementation > MiniProject_C/3_Implementation/build_actions/result_cppcheck.txt
      - name: Download results
        uses: actions/upload-artifact@v2
        with:
          name: cpp results
          path: MiniProject_C/3_Implementation/build_actions/cppcheck.txt
